---
# Site settings
title: Christopher McKenzie
baseurl: http://chrismckenzie.io/
email: chris@chrismckenzie.io
languageCode: en-us
metaDataFormat: yaml
newContentEditor: vim
SectionPagesMenu: "main"
publishdir: "public"
permalinks:
  blog: /:year/:month/:day/:title/
  packages: /:title
pygmentsStyle: "monokai"
disqusShortname: "chrismckenzieio"
watch: true
canonifyurls: true
params:
  twitter_username: TopherMcK
  github_username:  ChrisMcKenzie
  instagram_username: hobby_hobbiest
  google_userid: 112997148822003661332
  facebook_username: cmckenzie13
  description_title: A little about me
  description: |
    My name is Christopher McKenzie, 
    I am a Father, Senior Systems Engineer, and Go enthusiast in Upland, CA.
    I am a collector of hobbies you might say, I fly model aircraft, play
    guitar, and brew beer to name a few.
---
